/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVendorsRouteImport } from './routes/app.vendors'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRfqsRouteImport } from './routes/app.rfqs'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppQuotationsRouteImport } from './routes/app.quotations'
import { Route as AppPurchaseOrdersRouteImport } from './routes/app.purchase-orders'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppDeliveryRouteImport } from './routes/app.delivery'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppVendorsIdRouteImport } from './routes/app.vendors.$id'
import { Route as AppQuotationsCompareRouteImport } from './routes/app.quotations.compare'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRfqsRoute = AppRfqsRouteImport.update({
  id: '/rfqs',
  path: '/rfqs',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveryRoute = AppDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsIdRoute = AppVendorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVendorsRoute,
} as any)
const AppQuotationsCompareRoute = AppQuotationsCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppQuotationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/activity': typeof AppActivityRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/delivery': typeof AppDeliveryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/quotations': typeof AppQuotationsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/rfqs': typeof AppRfqsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/vendors': typeof AppVendorsRouteWithChildren
  '/app/quotations/compare': typeof AppQuotationsCompareRoute
  '/app/vendors/$id': typeof AppVendorsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/activity': typeof AppActivityRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/delivery': typeof AppDeliveryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/quotations': typeof AppQuotationsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/rfqs': typeof AppRfqsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/vendors': typeof AppVendorsRouteWithChildren
  '/app/quotations/compare': typeof AppQuotationsCompareRoute
  '/app/vendors/$id': typeof AppVendorsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/activity': typeof AppActivityRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/delivery': typeof AppDeliveryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/quotations': typeof AppQuotationsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/rfqs': typeof AppRfqsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/vendors': typeof AppVendorsRouteWithChildren
  '/app/quotations/compare': typeof AppQuotationsCompareRoute
  '/app/vendors/$id': typeof AppVendorsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/profile-setup'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/app/activity'
    | '/app/approvals'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/delivery'
    | '/app/invoices'
    | '/app/notifications'
    | '/app/profile'
    | '/app/purchase-orders'
    | '/app/quotations'
    | '/app/reports'
    | '/app/rfqs'
    | '/app/settings'
    | '/app/users'
    | '/app/vendors'
    | '/app/quotations/compare'
    | '/app/vendors/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/profile-setup'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/app/activity'
    | '/app/approvals'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/delivery'
    | '/app/invoices'
    | '/app/notifications'
    | '/app/profile'
    | '/app/purchase-orders'
    | '/app/quotations'
    | '/app/reports'
    | '/app/rfqs'
    | '/app/settings'
    | '/app/users'
    | '/app/vendors'
    | '/app/quotations/compare'
    | '/app/vendors/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/profile-setup'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/app/activity'
    | '/app/approvals'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/delivery'
    | '/app/invoices'
    | '/app/notifications'
    | '/app/profile'
    | '/app/purchase-orders'
    | '/app/quotations'
    | '/app/reports'
    | '/app/rfqs'
    | '/app/settings'
    | '/app/users'
    | '/app/vendors'
    | '/app/quotations/compare'
    | '/app/vendors/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vendors': {
      id: '/app/vendors'
      path: '/vendors'
      fullPath: '/app/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rfqs': {
      id: '/app/rfqs'
      path: '/rfqs'
      fullPath: '/app/rfqs'
      preLoaderRoute: typeof AppRfqsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotations': {
      id: '/app/quotations'
      path: '/quotations'
      fullPath: '/app/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders': {
      id: '/app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/delivery': {
      id: '/app/delivery'
      path: '/delivery'
      fullPath: '/app/delivery'
      preLoaderRoute: typeof AppDeliveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendors/$id': {
      id: '/app/vendors/$id'
      path: '/$id'
      fullPath: '/app/vendors/$id'
      preLoaderRoute: typeof AppVendorsIdRouteImport
      parentRoute: typeof AppVendorsRoute
    }
    '/app/quotations/compare': {
      id: '/app/quotations/compare'
      path: '/compare'
      fullPath: '/app/quotations/compare'
      preLoaderRoute: typeof AppQuotationsCompareRouteImport
      parentRoute: typeof AppQuotationsRoute
    }
  }
}

interface AppQuotationsRouteChildren {
  AppQuotationsCompareRoute: typeof AppQuotationsCompareRoute
}

const AppQuotationsRouteChildren: AppQuotationsRouteChildren = {
  AppQuotationsCompareRoute: AppQuotationsCompareRoute,
}

const AppQuotationsRouteWithChildren = AppQuotationsRoute._addFileChildren(
  AppQuotationsRouteChildren,
)

interface AppVendorsRouteChildren {
  AppVendorsIdRoute: typeof AppVendorsIdRoute
}

const AppVendorsRouteChildren: AppVendorsRouteChildren = {
  AppVendorsIdRoute: AppVendorsIdRoute,
}

const AppVendorsRouteWithChildren = AppVendorsRoute._addFileChildren(
  AppVendorsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeliveryRoute: typeof AppDeliveryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppQuotationsRoute: typeof AppQuotationsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppRfqsRoute: typeof AppRfqsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVendorsRoute: typeof AppVendorsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDeliveryRoute: AppDeliveryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppQuotationsRoute: AppQuotationsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppRfqsRoute: AppRfqsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppVendorsRoute: AppVendorsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from '../src 1/start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
